### ISSUE TITLE
When no IC2 doesn't work?

### ISSUE THREAD

**Issue by HanPrower** [LepkoQQ/EasyCrafting#10]
Full log:
http://pastebin.com/HdyeWunL

This gets spammed in console on 1.1.2 (I don't have IC2 installed, the only thing that may vaguely call IC2 is the NEIPlugins by mistaqur):

2012-12-06 08:14:24 [INFO] [Lepko-EasyCrafting] Started Worker Thread == T:Minecraft main thread
2012-12-06 08:14:24 [INFO] [Lepko-EasyCrafting] 1: Skipped recipe: vz@66545de9 == T:EasyCrafting-WorkerThread
2012-12-06 08:14:24 [INFO] [Lepko-EasyCrafting] 2: Skipped recipe: we@ed65498 == T:EasyCrafting-WorkerThread
2012-12-06 08:14:24 [INFO] [STDERR] Exception in thread "EasyCrafting-WorkerThread" java.lang.RuntimeException: java.lang.ClassNotFoundException: ic2.common.ElectricItem
2012-12-06 08:14:24 [INFO] [STDERR]     at ic2.api.ElectricItem.discharge(ElectricItem.java:51)
2012-12-06 08:14:24 [INFO] [STDERR]     at net.lepko.easycrafting.easyobjects.EasyItemStack.fromItemStack(EasyItemStack.java:67)
2012-12-06 08:14:24 [INFO] [STDERR]     at net.lepko.easycrafting.helpers.RecipeHelper.setAllRecipes(RecipeHelper.java:82)
2012-12-06 08:14:24 [INFO] [STDERR]     at net.lepko.easycrafting.helpers.RecipeHelper.run(RecipeHelper.java:133)
2012-12-06 08:14:24 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2012-12-06 08:14:24 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: ic2.common.ElectricItem
2012-12-06 08:14:24 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:76)
2012-12-06 08:14:24 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-06 08:14:24 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(Unknown Source)
2012-12-06 08:14:24 [INFO] [STDERR]     at java.lang.Class.forName0(Native Method)
2012-12-06 08:14:24 [INFO] [STDERR]     at java.lang.Class.forName(Unknown Source)
2012-12-06 08:14:24 [INFO] [STDERR]     at ic2.api.ElectricItem.discharge(ElectricItem.java:47)
2012-12-06 08:14:24 [INFO] [STDERR]     ... 4 more

**Comment by LepkoQQ** [comment]
I just looked and it seems its related to extrabees honeycrstal. I'll take a look at it.

**Comment by LepkoQQ** [comment]
This should be fixed for upcoming 1.5 release
